version: '3'
services:
  backend:
    build:
      context: ./backend    
      target: production
    environment:      
      - NODE_ENV=production
    command: npm run server-prod
  frontend:
    build:
      context: ./frontend      
      target: production
    environment:      
      - NODE_ENV=production
