version: '3'
services:
  backend:
    build:
      context: ./backend    
      args:
        - NODE_ENV=production
    environment:      
      - NODE_ENV=production
    command: npm run server-prod
  frontend:
    build:
      context: ./frontend      
      args:
        - NODE_ENV=production
    environment:      
      - NODE_ENV=production
