version: '3'
services:
  backend:    
    volumes:
      - ./backend/server.js:/backend/server.js:ro     
    environment:      
      - NODE_ENV=development
  frontend:   
    environment:      
      - NODE_ENV=development
