version: '3'
services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/backend:ro     
    environment:      
      - NODE_ENV=development
    command: npm run server-dev
  frontend:
    build:
      context: ./frontend      
      target: development
    environment:      
      - NODE_ENV=development
