version: '3'
services:
  backend:
    container_name: backendContainer
    build: ./backend
    volumes:
      - ./backend/server.js:/backend/server.js:ro
    ports:
      - "5000:5000"
    environment:
      - ports=5000
      - NODE_ENV=development
  frontend:
    container_name: frontendContainer
    build: ./frontend
    volumes:
      - ./frontend/src:/frontend/src:ro
    ports:
      - "3000:3000"
    env_file:
      - ./.env