version: '3'
services:
  backend:    
    volumes:
      - ./backend:/backend:ro     
    environment:      
      - NODE_ENV=development
  frontend:   
    environment:      
      - NODE_ENV=development
